<?php

namespace Tests\EOffice\Packages\Core;

use EOffice\Packages\Core\Application;
use EOffice\Packages\Testing\UnitTestCase;

/**
 * @covers \EOffice\Packages\Core\Application
 */
class ApplicationTest extends UnitTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_it_should_detect_base_path(): void
    {
        $app = new Application();
        $this->assertSame(getcwd(), $app->basePath());
    }
}
