Feature: homepage
  In order to ...
  As a ...
  I need to ...

  Scenario: browsing di halaman homepage
      Given saya berada di halaman homepage
      Then saya harus melihat tulisan "hello world"
